export const ANTECEDENT_REPOSITORY = Symbol('ANTECEDENT_REPOSITORY');
export const CLINICAL_ENTRY_REPOSITORY = Symbol('CLINICAL_ENTRY_REPOSITORY');
export const MEDICAL_HISTORY_REPOSITORY = Symbol('MEDICAL_HISTORY_REPOSITORY');